# Part 1：Python Basics with Numpy (optional assignment)

## 1 - Building basic functions with numpy

Numpy is the main package for scientific computing in Python. It is maintained by a large community (www.numpy.org). In this exercise you will learn several key numpy functions such as np.exp, np.log, and np.reshape. You will need to know how to use these functions for future assignments.

### 1.1 - sigmoid function, np.exp()

** Exercise: ** Build a function that returns the sigmoid of a real number x. Use math.exp(x) for the exponential function.

** Reminder: **
sigmoid(x)=$\frac{1}{1+e^{-x}}$ is sometimes also known as the logistic function. It is a non-linear function used not only in Machine Learning (Logistic Regression), but also in Deep Learning.
<img src="./images/week02-01.png" width="400" alt="" align=center />
To refer to a function belonging to a specific package you could call it using package_name.function(). Run the code below to see an example with math.exp().

In [1]:
import math

def basic_sigmoid(x):
    s = 1.0 / (1 + 1 / math.exp(x))
    return s

basic_sigmoid(3)

0.9525741268224334

Actually, we rarely use the “math” library in deep learning because the inputs of the functions are real numbers. In deep learning we mostly use matrices and vectors. This is why numpy is more useful.

In fact, if $x=(x_1,x_2,...,x_n)$ is a row vector then np.exp(x)np.exp(x) will apply the exponential function to every element of x. The output will thus be: np.exp(x)=($e^{x1},e^{x2},...,e^{xn}$)

In [2]:
import numpy as np

x = np.array([1, 2, 3])
print(np.exp(x))

[  2.71828183   7.3890561   20.08553692]


Furthermore, if x is a vector, then a Python operation such as s=x+3 or $s=\frac{1}{x}$ will output s as a vector of the same size as x.

In [3]:
x = np.array([1, 2, 3])
print(x+3)

[4 5 6]


** Exercise: ** Implement the sigmoid function using numpy.

Instructions: x could now be either a real number, a vector, or a matrix. The data structures we use in numpy to represent these shapes (vectors, matrices…) are called numpy arrays. You don’t need to know more for now. 

In [5]:
import numpy as np

def sigmoid(x):
    s = 1.0 / (1 + 1 / np.exp(x))
    return s

x = np.array([1, 2, 3])
sigmoid(x)

array([ 0.73105858,  0.88079708,  0.95257413])

> 数学公式编辑可参见：[LaTeX数学公式](http://blog.163.com/goldman2000@126/blog/static/167296895201221242646561/)